spring.application.name=processadordeimagem-api

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
server.port=8080

spring.amqp.deserialization.trust.all=true

spring.profiles.active=dev
