version: '3.8'

services:
  db:
    image: mariadb:10.2
    container_name: processador_imagem_db
    restart: always
    environment:
      MYSQL_DATABASE: processador_imagem_db
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3333:3306"
    volumes:
      - mariadb_data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: processadordeimagem-api
    restart: always
    depends_on:
      - db
      - rabbitmq
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://db:3306/processador_imagem_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
      SPRING_LIQUIBASE_ENABLED: true
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USERNAME: guest
      SPRING_RABBITMQ_PASSWORD: guest
    ports:
      - "8080:8080"
    volumes:
      - ./target:/target

volumes:
  mariadb_data:
