
# CRIACAO DE TABELAS

DROP TABLE IF EXISTS authorities;
CREATE TABLE authorities
(ID BIGINT NOT NULL,
 CREATION_DATE TIMESTAMP NOT NULL,
 CREATED_BY BIGINT NOT NULL,
 UPDATE_DATE TIMESTAMP,
 UPDATED_BY BIGINT,
 CODE VARCHAR(255) NOT NULL UNIQUE,
 DESCRIPTION LONGTEXT);
 
 